spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
spring.application.name=demo

# =========================================================
# CONFIGURACION DE HIBERNATE / JPA
# =========================================================
# 'update' crea o actualiza las tablas automáticamente en la BD segun las entidades @Entity definidas.
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de IntelliJ las consultas SQL que Hibernate ejecuta (Util para depuracion)
spring.jpa.show-sql=true

# URL de la API de Gemini
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent
gemini.api.key=${GEMINI_API_KEY:dummy-key-for-dev}

# URL de la api del conversor
exchangerate.api.url=https://v6.exchangerate-api.com/v6
exchangerate.api.key=COLOQUE SU API DE CONVERSOR